import { logger } from '../utils/logger.js';
import { executeESQuery } from '../services/elasticsearch.service.js';

/**
 * Elasticsearch Executor Node
 * 
 * This node executes the ES query generated by es_query_node.
 * Only runs if esQuery is present in state.
 * 
 * @param {Object} state - Current workflow state
 * @returns {Object} Updated state with ES query results
 */
export async function esExecutorNode(state) {
  logger.info('⚡ Executing es_executor_node');

  // Check if ES query is needed
  if (!state.needsESQuery || !state.esQuery) {
    logger.info('ℹ️  No ES query to execute, skipping');
    return {
      ...state,
      esData: null
    };
  }

  try {
    logger.info('🔍 Executing Elasticsearch query...');
    
    // Execute the ES query
    const esResult = await executeESQuery(state.esQuery);

    if (esResult.success) {
      logger.info(`✅ ES query executed successfully: ${esResult.total} documents found`);
      
      return {
        ...state,
        esData: {
          total: esResult.total,
          documents: esResult.documents,
          aggregations: esResult.aggregations,
          executedAt: new Date().toISOString()
        }
      };
    } else {
      // Check if ES was skipped (not available) vs actual error
      if (esResult.skipped) {
        logger.info('ℹ️  ES query skipped (Elasticsearch not available)');
      } else {
        logger.warn('⚠️  ES query execution failed:', esResult.error);
      }
      
      return {
        ...state,
        esData: {
          total: 0,
          documents: [],
          error: esResult.error,
          skipped: esResult.skipped || false
        }
      };
    }

  } catch (error) {
    logger.error('❌ Error in es_executor_node:', error);
    
    return {
      ...state,
      esData: {
        total: 0,
        documents: [],
        error: error.message
      }
    };
  }
}

