import { logger } from '../utils/logger.js';
import { executeQuery, executeMultipleQueries, extractField } from '../services/mysql.service.js';

/**
 * Extract table name from SQL query
 * 
 * @param {string} query - SQL query
 * @returns {string} Table name
 */
function extractTableName(query) {
  // Match "FROM table_name" or "FROM database.table_name"
  const fromMatch = query.match(/FROM\s+([`\w]+\.)?([`\w]+)/i);
  if (fromMatch) {
    // Remove backticks and return table name
    return fromMatch[2].replace(/`/g, '');
  }
  return 'unknown';
}

/**
 * Tag rows with their source table
 * 
 * @param {Array} rows - Query result rows
 * @param {string} tableName - Source table name
 * @returns {Array} Rows with _table metadata
 */
function tagRowsWithTable(rows, tableName) {
  return rows.map(row => ({
    ...row,
    _sourceTable: tableName
  }));
}

/**
 * Group rows by table
 * 
 * @param {Array} rows - All rows with _sourceTable
 * @returns {Object} Rows grouped by table name
 */
function groupRowsByTable(rows) {
  const grouped = {};
  rows.forEach(row => {
    const table = row._sourceTable || 'unknown';
    if (!grouped[table]) {
      grouped[table] = [];
    }
    grouped[table].push(row);
  });
  return grouped;
}

/**
 * SQL Executor Node
 * 
 * This node executes the SQL queries generated by sql_query_node.
 * It fetches actual data from the MySQL database and tags each row with its source table.
 * 
 * @param {Object} state - Current workflow state
 * @returns {Object} Updated state with SQL query results
 */
export async function sqlExecutorNode(state) {
  logger.info('⚡ Executing sql_executor_node');

  // Check if SQL query exists
  if (!state.sqlQuery) {
    logger.info('ℹ️  No SQL query to execute, skipping');
    return {
      ...state,
      sqlData: null
    };
  }

  try {
    logger.info('🗄️  Executing SQL queries...');
    
    const queries = Array.isArray(state.sqlQuery) ? state.sqlQuery : [state.sqlQuery];
    
    let result;
    
    if (queries.length === 1) {
      // Single query
      const query = queries[0];
      const tableName = extractTableName(query);
      
      result = await executeQuery(query);
      
      if (result.success) {
        logger.info(`✅ SQL query executed: ${result.rowCount} rows from ${tableName}`);
        
        // Tag rows with source table
        const taggedRows = tagRowsWithTable(result.rows, tableName);
        
        // Extract order_ids and customer_ids for ES query
        const orderIds = extractField(taggedRows, 'order_id');
        const customerIds = extractField(taggedRows, 'customer_id');
        
        logger.info(`📊 Extracted from SQL: ${orderIds.length} order_ids, ${customerIds.length} customer_ids`);
        
        return {
          ...state,
          sqlData: {
            success: true,
            rows: taggedRows,
            rowsByTable: { [tableName]: taggedRows },
            rowCount: result.rowCount,
            executionTime: result.executionTime,
            tablesQueried: [tableName],
            // Only order_ids and customer_ids for ES query
            orderIds: orderIds,
            customerIds: customerIds,
            executedAt: new Date().toISOString()
          }
        };
      } else {
        logger.warn('⚠️  SQL query execution failed:', result.error);
        
        return {
          ...state,
          sqlData: {
            success: false,
            error: result.error,
            rows: []
          }
        };
      }
      
    } else {
      // Multiple queries
      result = await executeMultipleQueries(queries);
      
      if (result.success) {
        logger.info(`✅ All SQL queries executed: ${result.totalRows} total rows`);
        
        // Tag rows from each query with their source table
        const allTaggedRows = [];
        const tablesQueried = [];
        
        queries.forEach((query, index) => {
          const tableName = extractTableName(query);
          tablesQueried.push(tableName);
          
          const queryResult = result.results[index];
          if (queryResult && queryResult.rows) {
            const taggedRows = tagRowsWithTable(queryResult.rows, tableName);
            allTaggedRows.push(...taggedRows);
            logger.info(`   - ${tableName}: ${queryResult.rows.length} rows`);
          }
        });
        
        // Group rows by table for easier analysis
        const rowsByTable = groupRowsByTable(allTaggedRows);
        
        // Extract order_ids and customer_ids for ES query
        const orderIds = extractField(allTaggedRows, 'order_id');
        const customerIds = extractField(allTaggedRows, 'customer_id');
        
        logger.info(`📊 Extracted from SQL: ${orderIds.length} order_ids, ${customerIds.length} customer_ids`);
        logger.info(`📊 Tables queried: ${tablesQueried.join(', ')}`);
        
        return {
          ...state,
          sqlData: {
            success: true,
            results: result.results,
            totalQueries: result.totalQueries,
            rowCount: result.totalRows,
            rows: allTaggedRows,
            rowsByTable: rowsByTable,
            tablesQueried: tablesQueried,
            // Only order_ids and customer_ids for ES query
            orderIds: orderIds,
            customerIds: customerIds,
            executedAt: new Date().toISOString()
          }
        };
      } else {
        logger.warn('⚠️  SQL queries execution failed:', result.error);
        
        return {
          ...state,
          sqlData: {
            success: false,
            error: result.error,
            results: []
          }
        };
      }
    }

  } catch (error) {
    logger.error('❌ Error in sql_executor_node:', error);
    
    return {
      ...state,
      sqlData: {
        success: false,
        error: error.message,
        rows: []
      }
    };
  }
}

